settings:
  name: BlueXP ransomware protection
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: BlueXP ransomware protection docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new in BlueXP ransomware protection
          url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about BlueXP ransomware protection
          url: /concept-ransomware-protection.html
        - title: Prerequisites
          url: /rp-start-prerequisites.html
        - title: Quick start
          url: /rp-start-quick-start.html
        - title: Set up BlueXP ransomware protection 
          url: /rp-start-setup.html
        - title: Access BlueXP ransomware protection
          url: /rp-start-login.html
        - title: Set up licensing
          url: /rp-start-licenses.html
        - title: Discover workloads
          url: /rp-start-discover.html 
        - title: Simulate a ransomware attack
          url: /rp-start-simulate.html  
        - title: Configure backup destinations and enable threat detection in the Settings option
          url: /rp-use-settings.html 
        - title: FAQ
          url: /rp-start-faq.html
    - title: Use BlueXP ransomware protection
      entries:
        - title: Use BlueXP ransomware protection overview
          url: /rp-use-overview.html 
        - title: View workload health using the Dashboard
          url: /rp-use-dashboard.html
        - title: Protect workloads
          entries: 
            - title: Protect workloads with ransomware protection strategies
              url: /rp-use-protect.html
            - title: Scan for personally identifiable data
              url: /rp-use-protect-classify.html 
        - title: Respond to a detected alert 
          url: /rp-use-alert.html
        - title: Recover from a ransomware attack
          url: /rp-use-recover.html
#       - title: Manage workloads 
#         url: /rp-use-manage.html
        - title: Download reports
          url: /rp-use-reports.html 
#   - title: Monitor ransomware protection jobs
#     url: /rp-use-monitor-jobs.html 
    - section: support
    - title: Reference
      entries:
        - title: Role-based access control privileges
          url: /rp-reference-roles.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
