settings:
  name: BlueXP ransomware protection
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: BlueXP ransomware protection docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about BlueXP ransomware protection
          url: /concept-ransomware-protection.html
        - title: Prerequisites
          url: /rp-start-prerequisites.html
        - title: Quick start
          url: /rp-start-quick-start.html
        - title: Set up BlueXP ransomware protection 
          url: /rp-start-setup.html
        - title: Access BlueXP ransomware protection
          url: /rp-start-login.html
        - title: Discover workloads
          url: /rp-start-discover.html  
        - title: FAQ
          url: /rp-start-faq.html
    - title: Use BlueXP ransomware protection
      entries:
        - title: Use BlueXP ransomware protection 
          url: /rp-use-overview.html 
        - title: View workload health using the Dashboard
          url: /rp-use-dashboard.html
        - title: Protect workloads
          url: /rp-use-protect.html
        - title: Respond to a detected alert 
          url: /rp-use-alert.html
        - title: Recover from a ransomware attack
          url: /rp-use-recover.html
#        - title: Manage workloads 
#          url: /rp-use-manage.html
#   - title: Monitor ransomware protection jobs
#     url: /rp-use-monitor-jobs.html 
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family


